# Generated by Django 5.0.3 on 2024-04-03 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(default='00:00')),
                ('time_out', models.TimeField(default='00:00')),
                ('description', models.CharField(max_length=256)),
                ('site_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='models.timesheets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_timesheets',
            },
        ),
    ]
