# Generated by Django 5.0.3 on 2024-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_timesheets_who_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOF', models.FloatField()),
                ('WFH', models.FloatField()),
            ],
        ),
    ]
