# Generated by Django 5.0.3 on 2024-04-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_configsalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_timesheets',
        ),
    ]
