# Generated by Django 5.0.3 on 2024-04-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_delete_user_timesheets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('datetime_requested', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[(0, 'rejected'), (1, 'pending'), (2, 'approved')], default=1, max_length=50)),
                ('who_signed', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
