# Generated by Django 5.0.3 on 2024-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_leave_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_requests',
            name='datetime_end',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leave_requests',
            name='datetime_requested',
            field=models.DateTimeField(auto_now_add=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leave_requests',
            name='datetime_start',
            field=models.DateTimeField(max_length=50),
        ),
    ]
