# Generated by Django 5.0.3 on 2024-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_leave_requests_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='time_out',
            field=models.TimeField(default='-', null=True),
        ),
    ]
