# Generated by Django 5.0.3 on 2024-04-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
