# Generated by Django 5.0.3 on 2024-04-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
