# Generated by Django 5.0.3 on 2024-04-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_displaytext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayText',
        ),
    ]
