# Generated by Django 5.0.3 on 2024-04-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_delete_displaytext'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
