# Generated by Django 5.0.3 on 2024-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_timesheets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='status',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
